### ISSUE TITLE
create new app

### ISSUE THREAD

**Issue by bojanm7** [DevExpress/devextreme-vue-template#2]
When trying to create new app with npx devextreme-cli new vue-app app-name, get errors:

The 'vue-app' application type is not valid
<img width="568" alt="Screenshot 2019-04-29 at 11 26 20" src="https://user-images.githubusercontent.com/8371532/56887350-ab578880-6a71-11e9-9616-cd285ac0206b.png">

**Comment by dxvladislavvolkov** [comment]
@bojanm7 hi,
We implemented the vue approach in version 1.1.0-beta.2. You can use tag 'next' to try this feature.
